
omic_hdf: "tcga_omic.hdf"
clinical_hdf: "tcga_clinical.hdf"

timestamp: "2016_01_28" # This is the most recent timestamp

firehose_get_url: "http://gdac.broadinstitute.org/runs/code/firehose_get_latest.zip"

cancer_types: ["ACC", "CESC", "HNSC", 
               "KIRC", "LGG", "LUSC", "PAAD", "READ", "STAD", 
               "THCA", "UCS", "BLCA", "CHOL", "DLBC", "GBM", 
               "KICH", "KIRP", "LIHC", "MESO", "PCPG", "SARC", 
               "THYM", "UVM", "BRCA", "COAD", "ESCA", 
               "LAML", "LUAD", "OV", "PRAD", 
               "SKCM", "TGCT", "UCEC"]
               #"COADREAD",
               #"STES", 
               #"GBMLGG", 
               #"KIPAN", 


# These flags identify nodes in the 
# Broad Firehose data processing DAG:
# http://gdac.broadinstitute.org/stddata-DAG.html
data_types:
    Methylation_Preprocess:       # Methylation data
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.Methylation_Preprocess.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.meth.by_mean.data.txt"
        workflow: "default"
    mRNAseq_Preprocess:           # mRNA-seq data
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.mRNAseq_Preprocess.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.uncv2.mRNAseq_RSEM_normalized_log2.txt"
        #workflow: "restore_barcodes"
        workflow: "default"
    Merge_rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data:
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.Merge_rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.Merge_rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.data.txt"
        workflow: "unused"
    RPPA_AnnotateWithGene:        # RPPA proteomic data
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.RPPA_AnnotateWithGene.Level_3.{timestamp_abbr}00.0.0"
        file_template: "{cancer_type}.rppa.txt"
        workflow: "default"
    CopyNumber_Gistic2: # CNA data (with "noise" from germline CNVs removed)
        run_type: "analyses"
        zip_template: "analyses__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}-TP.CopyNumber_Gistic2.Level_4.{timestamp_abbr}00.0.0"
        file_template: "all_data_by_genes.txt"
        workflow: "default"
    MutSigNozzleReport2CV:
        run_type: "analyses"
        zip_template: "analyses__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}-TP.MutSigNozzleReport2CV.Level_4.{timestamp_abbr}00.0.0"
        file_template: "sig_genes.txt"
        workflow: "unused"
    Mutation_Packager_Oncotated_Calls:
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.Mutation_Packager_Oncotated_Calls.Level_3.{timestamp_abbr}00.0.0"
        file_template: "MANIFEST.txt" 
        workflow: "featurize_mutations"
     

# Some files are missing from FireBrowse
missing_files:
    LAML: ["RPPA_AnnotateWithGene", "miRseq_Mature_Preprocess", "CopyNumber_Gistic2"]
    LIHC: ["RPPA_AnnotateWithGene"]
    MESO: ["Mutation_Packager_Oncotated_Calls", "MutSigNozzleReport2CV"]
    SKCM: ["CopyNumber_Gistic2"]
    UVM: ["RPPA_AnnotateWithGene"]

# ...or have non-standard names
extra_files:
    LAML:
        CopyNumber_Gistic2: "analyses__{timestamp}/LAML/{timestamp_abbr}/gdac.broadinstitute.org_LAML-TB.CopyNumber_Gistic2.Level_4.{timestamp_abbr}00.0.0/all_data_by_genes.txt"
        MutSigNozzleReport2CV: "analyses__{timestamp}/LAML/{timestamp_abbr}/gdac.broadinstitute.org_LAML-TB.MutSigNozzleReport2CV.Level_4.{timestamp_abbr}00.0.0/sig_genes.txt"
    LIHC:
        RPPA_AnnotateWithGene: "stddata__{timestamp}/LIHC/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.RPPA_AnnotateWithGene.Level_3.2016071400.0.0/LIHC.rppa.txt"
    SKCM:
        CopyNumber_Gistic2: "analyses__{timestamp}/SKCM/{timestamp_abbr}/gdac.broadinstitute.org_SKCM-TM.CopyNumber_Gistic2.Level_4.{timestamp_abbr}00.0.0/all_data_by_genes.txt"
        MutSigNozzleReport2CV: "analyses__{timestamp}/SKCM/{timestamp_abbr}/gdac.broadinstitute.org_SKCM-TM.MutSigNozzleReport2CV.Level_4.{timestamp_abbr}00.0.0/sig_genes.txt"


clinical_data_types:
    Clinical_Pick_Tier1: 
        run_type: "stddata"
        zip_template: "stddata__{timestamp}/{cancer_type}/{timestamp_abbr}/gdac.broadinstitute.org_{cancer_type}.Clinical_Pick_Tier1.Level_4.{timestamp_abbr}00.0.0"
        file_template: "All_CDEs.txt"


viz_options:
    mRNAseq_Preprocess: "--standardize"
    Methylation_Preprocess: ""
    RPPA_AnnotateWithGene: ""
    CopyNumber_Gistic2: ""
    Mutation_Packager_Oncotated_Calls: ""

